version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Build phase skipped or minimal"
  build:
    commands:
      - echo "No build artifact packing beyond source"

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - miniproject4-next/**/*
    - miniproject4-spring/**/*
